---
apiVersion: v1
kind: Secret
metadata:
  name: jayfray12-take2-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23JanusN/jayfray12-take2-gateway-gitops
